### ISSUE TITLE
Feature Request: Cross-Building package

### ISSUE THREAD

**Issue by vaporup** [Arsen6331/lure#1]
Hi,

just tried lure and it looks really promising.
I did a ```lure build``` which created a deb package because I am on a Ubuntu system.

It would be nice to create other package formats from the current Distro.
Something like:

```
LURE_PKG_FORMAT=apk lure build
LURE_PKG_FORMAT=rpm lure build
...
```

(similar to GOOS=windows go build)

**Comment by Arsen6331** [comment]
The issue is that it needs to know which overrides to use, so I'll need to set the entire distro rather than just the package format. This shouldn't be too difficult regardless.

**Comment by Arsen6331** [comment]
I've just finished implementing this in 4307278. You use it like so: `LURE_DISTRO=alpine LURE_PKG_FORMAT=apk lure build`.

**Comment by vaporup** [comment]
Great. Thank you
