### ISSUE TITLE
option to define folder name for source

### ISSUE THREAD

**Issue by Emerald-glitch** [Arsen6331/lure#10]
maybe just do it as PKGBUILD does it like this 
 'sirit::git+https://github.com/ReinUsesLisp/sirit'

**Comment by Arsen6331** [comment]
I already have a method for passing options. Most likely, it'll just be adding `?~dirname=sirit` or something similar, though in this particular case, the directory should already be called `sirit`, since that's the name of the repo.

**Comment by Emerald-glitch** [comment]
> I already have a method for passing options. Most likely, it'll just be adding `?~dirname=sirit` or something similar, though in this particular case, the directory should already be called `sirit`, since that's the name of the repo.

yeah, but in any case i think a explicit way to provide a name would be nice.

**Comment by Emerald-glitch** [comment]
Also, i noticed lure doesn't make a bare clone, instead it just clones a repo and wipes the whole src dir during next build. Wouldn't it be better to use do a bare clone ( git clone --mirror) and then using it to make a working repo, it will remove the need to clone big repos again and again, the bare clone can then be used to just fetch deltas.

**Comment by Arsen6331** [comment]
> Also, i noticed lure doesn't make a bare clone, instead it just clones a repo and wipes the whole src dir during next build. Wouldn't it be better to use do a bare clone ( git clone --mirror) and then using it to make a working repo, it will remove the need to clone big repos again and again, the bare clone can then be used to just fetch deltas.

That would require a bit of refactoring, so if you could open a separate issue for it, that would be nice.

**Comment by Arsen6331** [comment]
Implemented in c0e535c6309c4e5443890e7a57bf4ecb348757ac, documentation at https://github.com/Arsen6331/lure/blob/master/docs/build-scripts.md#sources.
