### ISSUE TITLE
A version function for git packages

### ISSUE THREAD

**Issue by Emerald-glitch** [Arsen6331/lure#11]
again, just like PKGBUILD a function to pull package version from the git repo would be nice, cause git packages don't really need modifications

**Comment by Arsen6331** [comment]
Yes, I was planning to add this today.

**Comment by Arsen6331** [comment]
Implemented in a42c9b27e793cd65e9a2c7f3dc15fc9c631cfe05, documentation at https://github.com/Arsen6331/lure/blob/master/docs/build-scripts.md#version. Thank you.
