### ISSUE TITLE
LURE Web interface

### ISSUE THREAD

**Issue by Arsen6331** [Arsen6331/lure#12]
Currently, the LURE repo is a simple Github repo that contains directories that represent packages. I would like to create a web interface similar to `aurweb` that hosts packages and shows information about them.

**Comment by Arsen6331** [comment]
I am currently working on this locally, so LURE development may be a bit slower until I'm done.

**Comment by JesseKoldewijn** [comment]
> I am currently working on this locally, so LURE development may be a bit slower until I'm done.

Hey man, I know ya wont know me but if you might want some help with setting up a webapp like the aurweb one I'd love to help out if needed.

Ps. dropped by here after hearing about the project in Brodie Robertson's video on youtube.

**Comment by Arsen6331** [comment]
I've just added a database to LURE. This should make the web interface much simpler and a lot easier to build.

**Comment by Arsen6331** [comment]
Here's a little preview of what I'm working on at the moment:

![image](https://user-images.githubusercontent.com/41810442/208325354-fd3823d7-c2ac-4fe8-a4d7-fc57aa8fe4fe.png)

![image](https://user-images.githubusercontent.com/41810442/208325380-be6a517f-21c3-4413-9cb2-41977edacc2d.png)

![image](https://user-images.githubusercontent.com/41810442/208325416-91618b65-a620-44fe-8278-caa934c84b93.png)

![image](https://user-images.githubusercontent.com/41810442/208325425-893d4f89-ced8-4317-9c30-21b38c0a4cfd.png)

![image](https://user-images.githubusercontent.com/41810442/208325439-46b36a92-690e-4efd-b734-5f4163530fc2.png)

**Comment by Arsen6331** [comment]
LURE Web is now available at https://lure.arsenm.dev!
