### ISSUE TITLE
`postinst` gets ignored for `deb` packages

### ISSUE THREAD

**Issue by zocker-160** [Arsen6331/lure#14]
Although according to the [documentation](https://github.com/Arsen6331/lure/blob/master/docs/build-scripts.md#scripts) this should not be happening.

I am using
```bash
scripts=(
    ['postupgrade']='postupgrade'
    ['postinstall']='postinst'
    ['preremove']='prerm'
    ['postremove']='postrm'
)
```

in the script, but the resulting `deb` package does only contain `prerm` and `postrm`.

It works fine for the archlinux package though.

**Comment by Arsen6331** [comment]
`postinstall` should be working in `.deb` packages. It is handled here: https://github.com/goreleaser/nfpm/blob/main/deb/deb.go#L598. I'll test this out and see if I can find out what's causing it.

**Comment by Arsen6331** [comment]
I cannot reproduce this issue. I tested in Debian and the post install script executed:

```text
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 's' instead of '/s_0.0.1-1_amd64.deb'
The following NEW packages will be installed:
  s
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/706 B of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 /s_0.0.1-1_amd64.deb s amd64 0.0.1-1 [706 B]
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package s.
(Reading database ... 6661 files and directories currently installed.)
Preparing to unpack /s_0.0.1-1_amd64.deb ...
Unpacking s (0.0.1-1) ...
Setting up s (0.0.1-1) ...
postinst
```

As you can see, the last line is `postinst`.

I used the following build script:

```bash
name='s'
version=0.0.1
release=1
desc='Script test'
homepage='https://example.com'
architectures=('amd64' 'aarch64' 'arm7' 'arm6' '386')

scripts=(
	['postupgrade']='postupgrade'
	['postinstall']='postinst'
	['preremove']='prerm'
	['postremove']='postrm'	
)

package() {
	echo "package()"
}
```

With all the scripts containing `echo` with their names.

**Comment by zocker-160** [comment]
Ok so after digging a bit deeper I found out that the `postinst` script is actually stored as `postrm` inside the deb file. 

That is not ok!

This causes issues when uninstalling the application.

**Comment by Arsen6331** [comment]
> Ok so after digging a bit deeper I found out that the `postinst` script is actually stored as `postrm` inside the deb file.
> 
> That is a problem, this causes issues when uninstalling the application.
> 
> `postinst` and `postrm` are not the same.
> Peek.2022-10-23.12-31.mp4

Ah. That is a bug that I just fixed in the latest commit,

**Comment by zocker-160** [comment]
Nice this also fixes this issue, now all scripts are in the deb as it should. 

I guess the `postrm` script got overwritten by the `postinst` as `postrm`, which is why the postinst was missing.

Thanks for fixing.
