### ISSUE TITLE
Do you think this can be integrated with Nix/NixOS?

### ISSUE THREAD

**Issue by pupbrained** [Arsen6331/lure#16]
I've been using Nix for the past few months now, and I love it. One thing I've definitely missed, though, is the AUR since I moved from arch. Nix's sandboxing techniques make me feel that it'd be harder to integrate LURE with, but there's lots of other PMs that work with nix (npm, cargo, go, etc). I'd love to know if you have any thoughts or plans on this.

**Comment by pupbrained** [comment]
One way of doing this (that I can think of) is taking a similar approach to nvfetcher, wherein you convert the PKG build info into a nix expression for the user to add to their system.

**Comment by Arsen6331** [comment]
It might be possible to do so, but currently all packaging is handled by `nfpm`. To do this, I will have to abstract that so I can add another packaging backend. I will see what this entails and get back to you.

**Comment by Arsen6331** [comment]
This will require very large refactoring and a lot of abstraction, so this is not planned for now. I may revisit it in the future, once the initial goals of LURE are met and it is stable.
