### ISSUE TITLE
lure completion for the package store and repositories

### ISSUE THREAD

**Issue by xpamych** [Arsen6331/lure#17]
Is it possible to add auto-completion to future plans to search for packages from operating system repositories and external repositories by pressing the tab button?

**Comment by Arsen6331** [comment]
Completed in 23fd711be278c59e7762f1e1ba5c10380ffc1e1d

**Comment by xpamych** [comment]
What about zsh?))

**Comment by Arsen6331** [comment]
I have included both bash and zsh completions

**Comment by xpamych** [comment]
Hm. When you click on tab, nothing happens.
![image](https://user-images.githubusercontent.com/16473797/206653113-a138b558-fc38-4b53-8ab3-5ef648433976.png)

**Comment by Arsen6331** [comment]
Looks like I forgot to include the completion files in the latest package. Just place this file: https://github.com/Arsen6331/lure/blob/master/scripts/completion/zsh at `/usr/share/zsh/site-functions/` with the name `_lure` (it should start with an underscore). Then, if you have completions enabled, just restart your terminal and it should work.

**Comment by xpamych** [comment]
It works! Thx)
