### ISSUE TITLE
Self updater or maybe package in distro repos

### ISSUE THREAD

**Issue by ErikReider** [Arsen6331/lure#23]
This is a very interesting project but it would be nice to be able to update it after installation in a seamless manor. Here's a few ideas of how this could be done:

- Self updater just like yay on Arch (Updates itself through the AUR)
- Package in distro repos which will be pretty annoying / difficult to maintain
- Some way to curl the latest release (.rpm, .deb, apk, etc...) just like GitHub allows you to do

Thanks in advance! :)

**Comment by ErikReider** [comment]
Something like this would begin to cover the third suggestion:
`curl -s https://gitea.arsenm.dev/api/v1/repos/Arsen6331/lure/releases | jq -r '.[0]["assets"] | map(select(.name | contains("'$(uname -m)'"))) | map( { (.name|tostring): . } ) | add'` (don't judge my jq "skills")

**Comment by Arsen6331** [comment]
This seems like it would be a good idea. I think it can be solved by adding LURE itself to the LURE repos.

**Comment by JamiKettunen** [comment]
I know on Void if `xbps` package manager itself is updated it makes you update `xbps`, so in this case I suppose if `lure` has an update it should be updated before anything else is done as well? I believe other distros/package managers would have something similar, not sure if it would be absolutely necessary though.
