### ISSUE TITLE
encoding/hex: invalid byte: U+0073 's'

### ISSUE THREAD

**Issue by xpamych** [Arsen6331/lure#25]
I wrote lure.sh for noisetorch, but an error occurs at the sources download stage.

[https://gitflic.ru/project/xpamych/xpamych-lure-repo/blob?file=noisetorch%2Flure.sh]()

![image](https://user-images.githubusercontent.com/16473797/197782565-b3787904-9785-4756-8dcc-5ce74c35decc.png)

**Comment by Arsen6331** [comment]
Ah, it looks like the `SKIP` is case-sensitive. I will fix that. For now, you can use `'SKIP'` instead of `'skip'`.

**Comment by Arsen6331** [comment]
Fixed in 27fb08d
