### ISSUE TITLE
Lure does not remove dependency

### ISSUE THREAD

**Issue by xpamych** [Arsen6331/lure#26]
lure does not remove the dependency along with the main package if it was also installed using lure

I discovered this with the syncthing package and its dependency, which I added to the repository

**Comment by Arsen6331** [comment]
LURE simply passes the dependencies to the package manager, so you can remove them using the same methods. On `apt`, it should be `sudo apt autoremove`, on `pacman`, `sudo pacman -Rss $(pacman -Qdtq)`, etc.
