### ISSUE TITLE
Packages get upgraded even if version number is unchanged on RPM distros

### ISSUE THREAD

**Issue by xpamych** [Arsen6331/lure#27]
If the package is built from the source code, then when updating, you will find out that the update is not required only after the compilation is finished. Maybe it's worth doing a check before compiling?

**Comment by Arsen6331** [comment]
It shouldn't even be updating if the version number hasn't changed. Have you experienced it doing that? If so, it's a bug.

**Comment by xpamych** [comment]
Yes, if I use ’’’ lure up''', the update of all packages installed in the system via lure begins.

**Comment by Arsen6331** [comment]
I can't replicate this issue. When I upgrade, I get the following output:

![image](https://user-images.githubusercontent.com/41810442/201565364-b9ee5b33-971b-4d21-9c15-1c9715517861.png)

**Comment by xpamych** [comment]
![2022-11-14_11-54](https://user-images.githubusercontent.com/16473797/201617417-f4729d6b-7353-423a-89e4-f05d9be0f96f.png)

**Comment by Arsen6331** [comment]
Fixed in 3f2ec8ebd3e51f9783a1f7ee7cd47b7dae964e0c
