### ISSUE TITLE
use scripts for preinstall or postinstall

### ISSUE THREAD

**Issue by xpamych** [Arsen6331/lure#28]
I can't figure out how to use preinstall scripts. For example, I need to include a 32-bit architecture or a non-free repository in debian. How can I do this in lure.sh ?

**Comment by Arsen6331** [comment]
The docs for scripts are here: https://github.com/Arsen6331/lure/blob/master/docs/build-scripts.md#scripts

**Comment by xpamych** [comment]
I tried to figure it out. Nothing is working out yet)
[https://gitflic.ru/project/xpamych/xpamych-lure-repo/blob?file=portproton%2Flure.sh]() 
 ```
scripts=(
['preinstall']='${repodir}/preinstall.sh'
)
```
![image](https://user-images.githubusercontent.com/16473797/205436805-289cf51b-8493-4dc4-8d3c-7e24cc57af70.png)
