### ISSUE TITLE
How to set maintainer field

### ISSUE THREAD

**Issue by vaporup** [Arsen6331/lure#3]
I created a lure repo for myself just for testing:  

https://github.com/vaporup/lure-repo

Building something brings this deprecation warning

```
DEPRECATION WARNING: Leaving the 'maintainer' field unset will not be allowed in a future version
```
I looked in the sourcecode of lure and nfpm
but could not figure out how to set this Maintainer field...

Checking the built packages, the Maintainer field is either set to some default or completely missing:

### deb

```
dpkg-deb -I ssh-tools_1.7-1_amd64.deb | grep Maint
```

```
Maintainer: Unset Maintainer <unset@localhost>
```

### rpm 
```
rpm -qip ssh-tools-1.7-1.x86_64.rpm | grep Packager
```

```
Packager    : 
```
### archlinux

in .PKGINFO of ssh-tools-1.7-1-x86_64.pkg.tar.zst

```
packager = Unknown Packager
```
### apk

Nothing in .PKGINFO of ssh-tools_1.7-1_x86_64.apk

**Comment by Arsen6331** [comment]
I will add that. The packager in Arch is completely different. It refers to the organization that packaged the software, rather than the maintainer.

**Comment by Arsen6331** [comment]
I've just added this functionality in 337e25c. Use the `maintainer` variable to set the maintainer.
