### ISSUE TITLE
Parse mandatory runtime deps from binaries and libraries

### ISSUE THREAD

**Issue by JamiKettunen** [Arsen6331/lure#32]
This is neat as then you don't have to manually always type these `deps` out for each package that are mandatory based on linked libraries, just ones that appear to be required on runtime if they're e.g. called from a shell script.

A database like this also avoids duplicating known names for certain packages on different distros across a bunch of `lure.sh`'s.

This could work similar to what Void's `xbps-src` does with [`04-generate-runtime-deps.sh`](https://github.com/void-linux/void-packages/blob/master/common/hooks/pre-pkg/04-generate-runtime-deps.sh) and [`06-shlib-provides`](https://github.com/void-linux/void-packages/tree/master/06-shlib-provides) `pre-pkg` hooks; for this we would at least need to map out each library `.so*`'s (seen in e.g. `objdump` / `ldd`  output of binaries) to package names for each distro in some way (while ideally avoiding duplicating `.so*` -> package names for each distro/arch if possible), for example [here's how Void does it](https://github.com/void-linux/void-packages/blob/master/common/shlibs).

On Arch PKGBUILDs you can also do e.g. [`depends+=(libmount.so libffi.so)` or `provides+=(libgio-2.0.so libglib-2.0.so libgmodule-2.0.so libgobject-2.0.so libgthread-2.0.so)`](https://github.com/archlinux/svntogit-packages/blob/693ba3b152195ae77ee559c8066e348eba9a8950/trunk/PKGBUILD#L61-L63) which mapping out the provided package names -> `.so*`s could also enable.

**Comment by Arsen6331** [comment]
This does seem like a good idea, but a very complicated one that doesn't seem to be within the scope of this project, You'd need to maintain a database of library files to package names for every supported distro, and even that wouldn't really handle anything but dynamic library dependencies.

**Comment by JamiKettunen** [comment]
I guess yeah... I'll close this, just wanted to share the idea
