### ISSUE TITLE
Don't remove dependencies that weren't installed by lure build

### ISSUE THREAD

**Issue by ErikReider** [Arsen6331/lure#33]
Aur helpers like yay and pikaur ask the user if they want to remove the build dependencies after install just like lure, but they only remove the build deps that were installed when the command was executed. Lure doesn't do this which could and has in my case, remove needed packages that were explicitly installed by the user

**Comment by Arsen6331** [comment]
Yeah, that would probably be a good idea. To implement that, I'll essentally just need to get the list of installed packages and see which are available before, then remove those from the list of build dependencies.

**Comment by Arsen6331** [comment]
Fixed in 07e41849e91496039bd2b9fd84a48aba3aedbf84, thanks.
