### ISSUE TITLE
FTL Error pulling repositories error="object not found"

### ISSUE THREAD

**Issue by xpamych** [Arsen6331/lure#37]
![image](https://user-images.githubusercontent.com/16473797/202548692-fb6c76bf-1485-4427-9c72-1e9019fb3a19.png)

![image](https://user-images.githubusercontent.com/16473797/202548739-b13bd55d-4a6d-4958-8880-3af774ed84ee.png)

**Comment by Arsen6331** [comment]
Interesting. This might be a bug in the git library. Was it working before?

**Comment by xpamych** [comment]
Yes, it's my main repo))

**Comment by Arsen6331** [comment]
It seems to be working fine for me. Can you test it again and see if it's fixed? Maybe it was just a temporary issue with the git service you're using.

**Comment by xpamych** [comment]
On debian doesn't work.

**Comment by Arsen6331** [comment]
I just tried with debian, and it's working

![image](https://user-images.githubusercontent.com/41810442/203153011-939c08a7-0eea-4231-ac66-07706ffdaa34.png)

What happens if you manually remove the repo using `rm -r ~/.cache/lure/repo/xpamych-repo` and then try again?

**Comment by xpamych** [comment]
Yes, it's work! Thx!
