### ISSUE TITLE
Storage of additional files alongside lure.sh in repos

### ISSUE THREAD

**Issue by JamiKettunen** [Arsen6331/lure#38]
Just curious: is this not possible currently? [`obsidian.desktop` creation in `lure-repo` for example is imho horrendous](https://github.com/Arsen6331/lure-repo/blob/61c735a/obsidian/lure.sh#L25-L36) currently and could just be stored as e.g. `obsidian/files/obsidian.desktop` alongside `obsidian/lure.sh` and installed to `${pkgdir}` from the directory.

For reference on [Void's `xbps-src` this is possible with the `${FILESDIR}` global variable](https://github.com/void-linux/void-packages/blob/master/Manual.md#global-variables).

**Comment by Arsen6331** [comment]
This should be possible with the new `$repodir` variable I added recently, which points to the path of the package in the repo. I agree that the desktop files shouldn't be made that way.

**Comment by xpamych** [comment]
> 

Is it already in 0.0.4?

**Comment by Arsen6331** [comment]
Yes, but it will be renamed in the future to `$scriptdir` because `$repodir` sounds more like the repository directory rather than the directory with the script.

**Comment by Arsen6331** [comment]
With the addition of `$repodir`/`$scriptdir`, this is complete, so I will close the issue
