### ISSUE TITLE
Which architecture to use for scripts

### ISSUE THREAD

**Issue by vaporup** [Arsen6331/lure#4]
I created a lure repo for myself just for testing:  

https://github.com/vaporup/lure-repo

The package ssh-tools is just a bunch of scripts.

I looked in the sourcecode of lure and nfpm but I am not sure
how to use the ```architectures``` var for scripts.

In Debian-based distros ```all``` is used  
and distros which use rpm, apk, pacman often it is ```noarch```

This is also reflected in the package filenames.

If I use ```architectures=('all')``` or completely remove the variable,  
the package filename and metadata in the package shows the current architecture of the build host.

### deb

```
dpkg-deb -I ssh-tools_1.7-1_amd64.deb | grep Arch
```

```
Architecture: amd64
```

### archlinux

In .PKGINFO of ssh-tools-1.7-1-x86_64.pkg.tar.zst

```
arch = x86_64
```

**Comment by Arsen6331** [comment]
You can set the architecture to `all`, and it will be translated to the proper name for the packaging format automatically.

**Comment by vaporup** [comment]
Hm, I tried using ```all```, I just wrongly wrote ```any``` in the issue text (changed it now).

**Comment by Arsen6331** [comment]
I just tried something that should fix it in ae9e294. Can you test it and see if this is still happening?

**Comment by vaporup** [comment]
Looks good. Could you do it for ```noarch``` as well? Then something like this works too:

```diff
diff --git a/ssh-tools/lure.sh b/ssh-tools/lure.sh
index 73ab1e4..80607c7 100644
--- a/ssh-tools/lure.sh
+++ b/ssh-tools/lure.sh
@@ -4,6 +4,8 @@ release=1
 desc='collection of various tools using ssh'
 homepage='https://github.com/vaporup/ssh-tools'
 architectures=('all')
+architectures_arch=('noarch')
+architectures_opensuse=('noarch')
 license=('GPLv3')
 
 deps=('openssh-client')

```

```all``` in Alpine is the ```any``` in Debian, so Alpine and others use ```noarch```

**Comment by Arsen6331** [comment]
The `all` architecture should be converted to the proper term for the format. For example, building an RPM converts it to `noarch` and building an Arch package converts it to `any` (arch uses `any`, not `noarch`).

If any of these conversions aren't happening, create an issue at https://github.com/goreleaser/nfpm as that would be a bug in their code.

**Comment by vaporup** [comment]
Checked it again and it looks good. apk und deb package file uses now `all`, the rpm `noarch` and archlinux `any`.
I must have mixed something up when testing before...
