### ISSUE TITLE
The function `version()`, and `architectures`  not working properly

### ISSUE THREAD

**Issue by SinTan1729** [Arsen6331/lure#40]
I'm trying to install [this script](https://github.com/SinTan1729/lure-repo/blob/main/bat/lure.sh). This works properly when tested locally. However, the installation fails when when installing from repo.

I added the `echo` in `package()` function, which shows that the `$version` isn't properly updated.

I think a better idea would be to run this `version()` function before getting the `source`, then this script won't have to do everything in `package()`.

Also, even though I added `all` inside `architectures`, I get the warning

"Your system's CPU architecture doesn't match this package. Do you want to build anyway?"

Replacing `all` by `amd64` seems to mitigate this, but I don't think that this should happen.

**Comment by Arsen6331** [comment]
> I added the echo in package() function, which shows that the $version isn't properly updated.

Ah, yes. The `version` variable is not updated. It just updates the version of the package LURE outputs. That is something I should implement.

> Replacing `all` by `amd64` seems to mitigate this, but I don't think that this should happen.

You're right, that's a bug

**Comment by Arsen6331** [comment]
The architecture issues should be fixed in da7830d

**Comment by Arsen6331** [comment]
The `version()` issue should be fixed in 8ceb61d. Can you please test and see if it works as you expect?

**Comment by SinTan1729** [comment]
@Arsen6331 It partly works. It does update the `version`, so I can properly download files using it inside `package()`. From the build log, it looks like `version()` is running before sources are pulled. But, putting the exact same URL in sources returns an error. I added `?~archive=false` at the end of that URL and it was clear that for some reason it was still using the placeholder `version` variable, instead of the updated one.
Here's the updated `lure.sh` that gives the error:
```
name='bat'
version=VERSION
release=1
desc='A cat(1) clone with syntax highlighting and Git integration'
homepage='https://github.com/sharkdp/bat'
architectures=('amd64')
maintainer='SinTan1729'
license=('APACHE-2.0' 'MIT')
provides=('bat')
conflicts=('bat')
git_repo='sharkdp/bat'

sources=("https://github.com/${git_repo}/releases/download/${version}/${name}-${version}-x86_64-unknown-linux-musl.tar.gz")
checksums=(SKIP)

version() {
    printf "$(curl --silent "https://api.github.com/repos/${git_repo}/releases/latest" | grep -Eo '"tag_name": "v(.*)"' | sed -E 's/.*"([^"]+)".*/\1/')"
}

package() {
	cd "./${name}-${version}-x86_64-unknown-linux-musl"
	install -Dm755 "./${name}" "${pkgdir}/usr/local/bin/${name}"
	install -Dm644 "./${name}.1" "${pkgdir}/usr/local/share/man/man1/${name}.1"
	command -v fish &> /dev/null && install -Dm644 "./autocomplete/${name}.fish" "${pkgdir}/usr/share/fish/completions/${name}.fish"
	command -v zsh &> /dev/null && install -Dm644 "./autocomplete/${name}.zsh" "${pkgdir}/usr/share/zsh/site-functions/_${name}"
	command -v bash &> /dev/null && install -Dm644 "./autocomplete/${name}.bash" "${pkgdir}/usr/share/bash-completion/completions/${name}"
}
```

**Comment by Arsen6331** [comment]
Yeah, there seems to be a bit of a technical issue with making that work. The parser library resolves the variables inside the strings when they're being parsed, which means that by the time I run the function, the string has already been resolved and contains the `VERSION` string. I'm going to need to think a bit about how to handle this.

**Comment by Arsen6331** [comment]
Alright, I've done some research. I don't think what you want exactly will be possible because of the fact that some packages, especially those using git sources, will need the repo cloned in order to calculate the version number in the first place. However, I do think the strings should be updated with the new version when it's cloned. The problem is only with the fact that `version()` has to run before the sources are fetched.

Usually, similar AUR scripts hardcode the version numbers from what I've seen. If you can find an example of an AUR package that works like this, please send me a link so I can see exactly how it's done there.

**Comment by SinTan1729** [comment]
> Alright, I've done some research. I don't think what you want exactly will be possible because of the fact that some packages, especially those using git sources, will need the repo cloned in order to calculate the version number in the first place. However, I do think the strings should be updated with the new version when it's cloned. The problem is only with the fact that `version()` has to run before the sources are fetched.
> 
> Usually, similar AUR scripts hardcode the version numbers from what I've seen. If you can find an example of an AUR package that works like this, please send me a link so I can see exactly how it's done there.

You're right that it'd cause problems for `git` packages. I don't have any similar AUR packages either. In the few AUR packages I maintain, I also use hardcoded version numbers. I guess my usecase here is rather an edge case, where my main goal is to automatically update the packages without ever (as long as there's no major packaging change upstream) updating the `lure.sh` file again. Right now, I'm achieving this using a separate update script. It works as per my need.
One question, is it currently possible to get a list of packages installed using `lure`? I'm sure it's somewhere since `lure up` knows which packages to check.

**Comment by Arsen6331** [comment]
`lure up`  knows which packages to check by cross-referencing installed packages from the package manager with the packages in the repo. I don't have a command for listing those in particular. I should add that. Can you create a new issue for that?

**Comment by SinTan1729** [comment]
Yeah, sure.
