### ISSUE TITLE
Lure Needs a Professional Logo

### ISSUE THREAD

**Issue by Elagoht** [Arsen6331/lure#42]
Others may help, it must be, and would be great. I want to add it on my website and YouTube thumbnails.

**Comment by Arsen6331** [comment]
I agree, but I'm not great at making logos. The best I have is the [lure-repo-bot](https://github.com/lure-repo-bot) logo, which looks fine but doesn't look great in light mode, which some people will want to use.

**Comment by Elagoht** [comment]
Others may want to help :)

**Comment by Arsen6331** [comment]
Currently, https://lure.arsenm.dev (#12) is using the default Svelte icon for its favicon. When a LURE icon is created, I will replace that with it.

**Comment by Arsen6331** [comment]
Here's what I have right now. I think this is a pretty good logo that would look good on many different backgrounds and would probably be pretty recognizable:

![candidate-1](https://user-images.githubusercontent.com/41810442/209066727-32cd74f6-7e31-48aa-8454-67be643f74bf.svg)

**Comment by Arsen6331** [comment]
I've gone ahead and updated https://lure.arsenm.dev. If everyone is happy with it, I'll close this issue.

**Comment by Elagoht** [comment]
On my phone I can't see half of the letter E but the logo looks OK. We can close this issue.

**Comment by Arsen6331** [comment]
> Is it supposed to render like this on the site? It looks like it's cut off partially ![image](https://user-images.githubusercontent.com/47358222/209116099-30cd99d7-2c62-416c-9f2d-afe61e8abdae.png)

> On my phone I can't see half of the letter E but the logo looks OK. We can close this issue.

Interesting, it's an SVG, it should be showing the whole thing, but that's a different issue, so I'll close this now. Thanks
