### ISSUE TITLE
[feature-request] Improvements for lure ls

### ISSUE THREAD

**Issue by SinTan1729** [Arsen6331/lure#43]
I would like to suggest some improvements to `lure ls`.
1. As per discussion in #40, add an optional argument for `lure ls`, presumably `lure ls installed`, to only list installed packages. Almost all other package managers provide this (e.g. `pacman -Q`, `paru -Q`, `apt list --installed`, `dnf list --installed` etc.), so I think this is a very important feature to have.
2. Group packages by repository when listing them. This should be similar to what `dnf list --installed` outputs.
3. Instead of cross-referencing with the package manager each time when getting this list described in 2 (also applies to `lure up`), maybe it'd be a better idea to have a list somewhere. A simple `txt` or `json` file should suffice.

**Comment by Arsen6331** [comment]
1. I agree. I think something like `lure ls -I` and `lure ls --installed`
2. I agree as well
3. Unfortunately, this is not possible. Because LURE generates native packages and installs them via the package manager, they can be removed by the package manager without LURE knowing. Luckily, cross-referencing the packages is relatively fast and easy.

**Comment by SinTan1729** [comment]
Ah yes, 3 is not plausible then.

**Comment by Arsen6331** [comment]
The `-I` and `--installed` flags have been added in 7d00c7b5fb340d0720ef163dffa5b1b837ca5a37. Can you test it and see if it works as you expect?

**Comment by SinTan1729** [comment]
> The `-I` and `--installed` flags have been added in [7d00c7b](https://github.com/Arsen6331/lure/commit/7d00c7b5fb340d0720ef163dffa5b1b837ca5a37). Can you test it and see if it works as you expect?

I'm getting a build error.
```
./info.go:62:12: syntax error: unexpected EOF, expecting }
make: *** [Makefile:2: lure] Error 2
```

**Comment by Arsen6331** [comment]
Oh, looks like I missed a closing brace. Fixed.

**Comment by SinTan1729** [comment]
It's not working. I'm only getting this:
```
1:29AM INF Pulling repository name="default"
1:29AM INF Repository up to date name="default"
1:29AM INF Pulling repository name="personal"
1:29AM INF Repository up to date name="personal"
```
Same output for `lure ls -I` and `lure ls`.

**Comment by Arsen6331** [comment]
Can you try removing the cache directory and then try it again? Just use `rm -r ~/.cache/lure`

**Comment by SinTan1729** [comment]
It seems to work now. Although I'd like to make a few suggestions.
1. `ls -I` should not ask for superuser permission as package listing is provided for normal users.
2. Maybe it's a good idea to print the versions received from the package manager in case of `ls -I`, then it'd show proper versions for git packages as well.

**Comment by Arsen6331** [comment]
1. df72d95ab764e163f646a25d532526b6848d4970
2. a106100312f4bec569a314f5a596fa22dff2b9c5

**Comment by SinTan1729** [comment]
It works perfectly now. Thanks for all your work.
