### ISSUE TITLE
Deps i686 conflicting requests

### ISSUE THREAD

**Issue by xpamych** [Arsen6331/lure#45]
does not pick up dependencies for Fedora
![Screenshot_20221203_172132](https://user-images.githubusercontent.com/16473797/205445649-837900fd-09cb-41fa-a7fa-faa0d74997ad.png)

**Comment by xpamych** [comment]
in РЕД ОС some problem 
![image](https://user-images.githubusercontent.com/16473797/205446271-d4d72303-317c-404d-9595-87f032c43700.png)

**Comment by Arsen6331** [comment]
That's interesting. It can't find packages when installing through LURE but finds them when you run the command manually.

This is weird because LURE simply adds the dependencies you specify in the build script to the package and then sends that to DNF, so it should find them if you can run a command to install them.

**Comment by Arsen6331** [comment]
I saw this comment: https://github.com/Arsen6331/lure/issues/28#issuecomment-1336131924, and I do know why that's happening. You need to enable the architecture you want to install for. For example, `sudo dpkg --add-architecture i386` followed by `sudo apt update`. Then, it should be able to find the dependencies. I just tested this myself and it worked.

**Comment by xpamych** [comment]
The point was just to have the script turn on the architecture, so as not to do it manually)

> I saw this comment from you: [#28 (comment)](https://github.com/Arsen6331/lure/issues/28#issuecomment-1336131924), and I do know why that's happening. You need to enable the architecture you want to install for. For example, `sudo dpkg --add-architecture i386` followed by `sudo apt update`. Then, it should be able to find the dependencies. I just tested this myself and it worked.

**Comment by xpamych** [comment]
The most interesting thing is how it works

![image](https://user-images.githubusercontent.com/16473797/205455902-0bf778a4-6e08-4920-a1a1-a41ec1f08a37.png)


> That's interesting. It can't find packages when installing through LURE but finds them when you run the command manually.
> 
> This is weird because LURE simply adds the dependencies you specify in the build script to the package and then sends that to DNF, so it should find them if you can run a command to install them.

**Comment by Arsen6331** [comment]
Ah, so what I think happened, is LURE tried to install the build dependencies before running any functions, and because you hadn't added the architecture yet, it failed. Anyway, I think it's not a great idea to add the architecture in the script. Maybe I could try to add a way to check which architectures are needed and warn the user if they're not available.

**Comment by xpamych** [comment]
This works by specifying the name of the desired dependency as an installation of a separate package via lure. But it does not work when installing the package when it is a dependency.

**Comment by Arsen6331** [comment]
That means that for some reason, DNF can't use that package as a dependency. When you install directly, it just sends that to the package manager. When you build a package with dependencies, it places all the dependencies in the package's metadata and then DNF is responsible for finding and installing them. I wonder how normal DNF packages use 32-bit dependencies.

**Comment by Arsen6331** [comment]
Ok, so it seems DNF and YUM based distros handle 32-bit dependency names differently from package names. You need to use `mesa-dri-drivers(x86-32)` as the dependency name. The same applies for the other dependencies.

**Comment by Arsen6331** [comment]
Since this is not a LURE issue, I will close this now

**Comment by xpamych** [comment]
Thx for solution!
