### ISSUE TITLE
Install bash/zsh shell completions (Makefile + install.sh)

### ISSUE THREAD

**Issue by JamiKettunen** [Arsen6331/lure#46]
Related: https://github.com/Arsen6331/lure/issues/17#issuecomment-1343974763

These should be integrated to the [`Makefile`](https://github.com/Arsen6331/lure/blob/master/Makefile) and [`install.sh` script](https://github.com/Arsen6331/lure/blob/master/scripts/install.sh).

As for the Makefile I'd like to ask for a separate e.g. `installmisc` target for non-binary files (which `install` depends on) so they can be called separately from e.g. the Void package build template where (cross-)building Go packages is handled [with a build-style](https://github.com/void-linux/void-packages/blob/master/common/build-style/go.sh) and [a corresponding environment](https://github.com/void-linux/void-packages/blob/master/common/environment/build-style/go.sh), and for non-binaries just this would be then needed:
```sh
post_install() {
    make PREFIX=/usr DESTDIR=${DESTDIR} installmisc
}
```
I previously sent https://lists.sr.ht/~craftyguy/superd/patches/36158 which [the Void package](https://github.com/void-linux/void-packages/blob/master/srcpkgs/superd/template) handles in a similar way

Perhaps a bit off-topic for this issue but there also should be an installation path `$(DESTDIR)$(PREFIX)/...` paradigm for the files with `PREFIX` defaulting to `/usr/local` in the Makefile so distributions can override these for packaging purposes.

**Comment by Arsen6331** [comment]
Done in eb4e2281fac3f2c9240c24dbc148948516c80263
