### ISSUE TITLE
Zombie packages

### ISSUE THREAD

**Issue by SinTan1729** [Arsen6331/lure#47]
I made a typo in the name of one of the packages in my repo. After fixing that name, `lure ref` does fetch the new package, but it also keeps the old one (i.e. it shows up in `lure list`). Had to manually delete `~/.cache/lure/` and `lure ref` to get rid of it.

**Comment by Arsen6331** [comment]
It probably stayed in the database. It should be fixed by `lure fix`, which essentially does the same thing as you did. I'll try to fix the repo pull code so it deletes the old package.

**Comment by SinTan1729** [comment]
Ah. I missed the `lure fix` option. I guess my case is kind of an edge case, and since there's already somewhat of a solution, it's acceptable.
