### ISSUE TITLE
[feature request] Add config option to ignore package updates

### ISSUE THREAD

**Issue by SinTan1729** [Arsen6331/lure#48]
I have some packages (e.g. `syncthing`) that are available in the `default` repo, but but I want them not to be touched by `lure` as my distro repositories already handle it and I'd rather stay with that version. It'd be great if there were an option to ignore certain packages. It'd be useful for `git` packages too, where I might not wanna update them every time. Also, if I want to stick to a version for any particular reason (e.g. bugs).

**Comment by Arsen6331** [comment]
Good idea, I'll add that.

**Comment by Arsen6331** [comment]
I've added a new `ignorePkgUpdates` field to the config in 22a74aa79312fec041ee3e1ea751dbc7dbe24340, can you test to see if it works as you expect?

**Comment by Arsen6331** [comment]
It's an array of strings, so

```toml
ignorePkgUpdates = [
	"syncthing",
]
```

**Comment by SinTan1729** [comment]
It works perfectly, thanks.
