### ISSUE TITLE
Make target to install miscellaneous non-binary files

### ISSUE THREAD

**Issue by JamiKettunen** [Arsen6331/lure#49]
A separate e.g. `installmisc` target for non-binary files (which `install` depends on) would be nice so it can be called separately from e.g. the Void package build template where (cross-)building Go packages is handled [with a build-style](https://github.com/void-linux/void-packages/blob/master/common/build-style/go.sh) and [a corresponding environment](https://github.com/void-linux/void-packages/blob/master/common/environment/build-style/go.sh), and for non-binaries just this would be then needed:
```sh
post_install() {
    make PREFIX=/usr DESTDIR=${DESTDIR} installmisc
}
```
I previously sent https://lists.sr.ht/~craftyguy/superd/patches/36158 which [the Void package](https://github.com/void-linux/void-packages/blob/master/srcpkgs/superd/template) handles in a similar way.

Copied mostly from #46 as I didn't get any particular feedback to this suggestion yet.

**Comment by JamiKettunen** [comment]
I suppose for now it's a bit redundant (at least in case of Void) as the same can be accomplished pretty easily also with:
```sh
post_install() {
    vcompletion scripts/completion/bash bash
    vcompletion scripts/completion/zsh zsh
}
```
Just thinking in terms of future additions it might become more complicated to keep maintaining.

**Comment by Arsen6331** [comment]
Done in 8a1d0f4f54be6124bb45ed89c82f9f958df74d1a, thanks
