### ISSUE TITLE
Setting up a document/website to search for a depencency/package and list the names on all distros

### ISSUE THREAD

**Issue by RMED24** [Arsen6331/lure#50]
The title is a bit strange, but I'll explain the idea:

We are all aware of the fact that dependencies are named different things on different distros. (Such as LibX11-dev on debian distros being called LibX11-devel on RPM distros). These being called different things is what the lure is trying to solve already.

However, if you want to make this a lot easier for developers, my idea is to have a website to search for these packages and automatically give the known name across each distro. This would be much better as right now I would have to guess what a dependency name on one distro would be on a different one, or just frantically google until you eventually get your answer. A website would make this easier for developers to automatically add support for each distro they figure out the package name, and may just get more developers interested in publishing to the lure.

Maybe this checking dependencies for each distro has been done for some other project, and if so I would be interested in viewing that website (as ironically enough it would help me figure out some dependencies I need to compile a program right now)

Thanks!

**Comment by Arsen6331** [comment]
Is https://repology.org/ what you're looking for? I tried to make a tool to automatically resolve dependencies via repology's API, but unfortunately, they group multiple packages under one project, so there's no way to ensure you're getting the same package unless someone actually looks at it. For example, if you go to the dbus project, you get `dbus`, `dbus-x11`, `dbus-doc`, etc.

**Comment by RMED24** [comment]
> Is https://repology.org/ what you're looking for? I tried to make a tool to automatically resolve dependencies via repology's API, but unfortunately, they group multiple packages under one project, so there's no way to ensure you're getting the same package unless someone actually looks at it. For example, if you go to the dbus project, you get `dbus`, `dbus-x11`, `dbus-doc`, etc.

I had a look at that website and whilst it is good, it's not perfect and definitely lacks support for 1 to 1 dependencies. I searched libx11-dev (that package is still clear in my mind rn), and on fedora 37 it said it was just called libx11, even though that wasn't 100% true

**Comment by RMED24** [comment]
I say this, because in the past I've used a program where it was picky and wouldn't work properly unless you had libx11 and not the development package. As in it would just crash otherwise

**Comment by Arsen6331** [comment]
I don't think this is in the scope of this project. While such a service would be extremely useful, and I can think of at least one way to implement it (cross-reference files provided by packages in each repo), that is not something that should be implemented inside LURE. I might think about creating something like that when I have some time. Thanks.
