### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by JamiKettunen** [Arsen6331/lure#51]
From what I could gather right now the `lure` CLI tool will always print messages in English, it would be great if translations/localization support was implemented to increase the reach of this tool.

For package `lure.sh` files at least `desc` should get localized/translated also one way or another as found in the discussion on https://github.com/Arsen6331/lure-repo/pull/30; one way to go about this would be to store the translation along with the package directly with e.g.
```sh
desc='User-friendly tool for working with Active Directory domains and group policies'
desc_ru='user-friendly инструмент для Linux для работы с доменом Active Directory и групповыми политиками.'
```
Perhaps the translations should be in a separate file to avoid unnecessary merge conflicts etc. but that's more of an implementation detail if this is the way decided to go forward with.

Another way to potentially deal with `desc` translation would be to depend on a CLI translator tool such as https://www.soimort.org/translate-shell/, but that might not be ideal for a number of reasons, perhaps even a combination of the 2 can be implemented, i.e. if localization of the UI language is configured via `LC_*` or so and `desc_<lang>` exists use that (added in case automatic translation is bad for example), otherwise fallback to `trans -brief "${desc}"`.

**Comment by Arsen6331** [comment]
> From what I could gather right now the lure CLI tool will always print messages in English, it would be great if translations/localization support was implemented to increase the reach of this tool.

I've thought of this, and I think it's a good idea. I just haven't gotten around to implementing it.

> For package lure.sh files at least desc should get localized/translated also one way or another as found in the discussion on https://github.com/Arsen6331/lure-repo/pull/30; one way to go about this would be to store the translation along with the package directly with e.g.

I agree, and I do think your solution is good, but with a slight modification. I would do it with a `localize` command that would be implemented as a helper command:

```bash
desc="$(localize desc en)"
desc_en = '...'
desc_ru = '...'
```

The command usage would be `localize <variable> <fallback language>`.

> Another way to potentially deal with desc translation would be to depend on a CLI translator tool such as [soimort.org/translate-shell](https://www.soimort.org/translate-shell/), but that might not be ideal for a number of reasons

Yeah, that doesn't seem like a very good idea. I think storing the translations in the script would be better.

**Comment by Arsen6331** [comment]
Localization for packages is now working:

![image](https://user-images.githubusercontent.com/41810442/211963402-5e49d894-8021-4757-9fa8-87afa019df72.png)

**Comment by Arsen6331** [comment]
Next, I'll be adding a translation system for LURE's logger so that the messages it prints can be localized.

**Comment by Arsen6331** [comment]
The LURE command itself now has localization support, with the translations stored in the [translations directory](https://github.com/Arsen6331/lure/tree/master/translations):

![image](https://user-images.githubusercontent.com/41810442/212232139-2308499c-9b3b-445a-940e-b5585611e9ab.png)

**Comment by Arsen6331** [comment]
Now I will just write documentation and if you think it looks good, I can close this. @JamiKettunen @xpamych

**Comment by xpamych** [comment]
I tried it, I like it, until I found problems

**Comment by JamiKettunen** [comment]
@xpamych Please elaborate on the problems you found, can't fix them if we don't know what those might be ^^

**Comment by xpamych** [comment]
> @xpamych Please elaborate on the problems you found, can't fix them if we don't know what those might be ^^

Oops, I missed the "not" 🤣

**Comment by Arsen6331** [comment]
> Please elaborate on the problems you found, can't fix them if we don't know what those might be ^^

I think they meant that they haven't found any problems so far.

**Comment by Arsen6331** [comment]
Since no one seems to be reporting any issues, I'll close this now. Please open a new issue if you find any issues. Thanks.
