### ISSUE TITLE
Suggestion for improvement. Continue the installation with compilation when the password timeout expires.

### ISSUE THREAD

**Issue by xpamych** [Arsen6331/lure#55]
When installing a package that requires compilation in ArchLinux via yay and the time for entering the password expires, when the installation command is run again, it continues, in lure we start from the beginning. It may be worth considering the possibility of continuing the installation so as not to compile again.

**Comment by Arsen6331** [comment]
Done in bd769468a939a99893a595f75eddbf0870f934a5
