### ISSUE TITLE
Does not check if the package is installed before compilation

### ISSUE THREAD

**Issue by xpamych** [Arsen6331/lure#56]
![image](https://user-images.githubusercontent.com/16473797/211200300-1fa92f37-4252-45d7-b527-3a38e43b30c5.png)

**Comment by xpamych** [comment]
For binary packages, it is also visible that a package is created from 0 first and only after that it shows that it is already installed in the system.
![image](https://user-images.githubusercontent.com/16473797/211200344-bd92c21e-c937-4533-8033-3f7a47cb314f.png)

**Comment by Arsen6331** [comment]
This is intentional and is the same as what most AUR helpers do. The reason is because you may want to rebuild the package. However, maybe I can print a warning about it being installed already.

**Comment by Arsen6331** [comment]
I've added a warning for installed packages
