### ISSUE TITLE
lure-bin missing from AUR

### ISSUE THREAD

**Issue by SinTan1729** [Arsen6331/lure#59]
The package `lure-bin` as listed in the README is missing from AUR.

**Comment by Arsen6331** [comment]
The package has been renamed to `linux-user-repository-bin` because there is another project with the package name `lure` and `lure-git`, so `lure-bin` makes it seem related. If you click the badge, it takes you to the new package.

**Comment by SinTan1729** [comment]
I see. In that case, I think the link under packages in README should also be changed to the new one.

Also, the new AUR package isn't working. There are no releases in the GitHub page, so it can't find the archive. I replaced the github links with your gitea repo, but then the checksums aren't matching.

**Comment by SinTan1729** [comment]
Also, your `lure-repo` version of `lure-bin` is stuck at version `0.0.6`. If you use GoReleaser for that too, that might be another potential bug.

**Comment by Arsen6331** [comment]
The `lure-repo` package has been updated. I am working on the GoReleaser bug.

**Comment by Arsen6331** [comment]
The AUR package is fixed, should be working now. Thanks.
