### ISSUE TITLE
upgrade, info, refresh, and list commands don't work as expected

### ISSUE THREAD

**Issue by aatmasaat** [Arsen6331/lure#6]
i'm using linux mint 20.2 uma and have built lure using latest commit 46e0343

1. `./lure upgrade` does nothing when there are packages to be upgraded
```bash
~/projects/lure ❯ apt list --upgradable -a
Listing... Done
timeshift/uma 22.06.5+una amd64 [upgradable from: 20.11.1.1+ulyssa]
timeshift/now 20.11.1.1+ulyssa amd64 [installed,upgradable to: 22.06.5+una]
timeshift/focal 20.03+ds-2 amd64

~/projects/lure ❯ ./lure upgrade
5:33AM INF There is nothing to do.
~/projects/lure ❯
```

2. `./lure info <pkg>` command fails no matter what
```bash
~/projects/lure ❯ ./lure info firefox
5:38AM FTL Error finding package error="package 'firefox' could not be found in any repository"
~/projects/lure ❯
```

3. `./lure refresh` always gives same output
```bash
~/projects/lure ❯ ./lure refresh
5:40AM INF Pulling repository name="default"
5:40AM INF Repository up to date name="default"
~/projects/lure ❯
```

4. `./lure list` shows only single result
```bash
~/projects/lure ❯ ./lure list
itd-bin 0.0.7
~/projects/lure ❯
```

shouldn't `listCmd` function be something like this?
```golang

func listCmd(c *cli.Context) error {
	mgr := manager.Detect()
	if mgr == nil {
		log.Fatal("Unable to detect supported package manager on system").Send()
	}

	pkgs, _ := mgr.ListInstalled()
	for name, version := range pkgs {
		fmt.Println(name, version)
	}

	return nil
}

```

this prints all the installed packages

**Comment by Arsen6331** [comment]
The reason is because these packages are meant for LURE itself.

- `lure refresh` updates the LURE repos, if there are any updates to fetch
- `lure upgrade` upgrades any LURE packages that need updates
- `lure info` shows information about packages in LURE repos
- `lure list` lists all packages in the LURE repos

I'll change the help screen text in order to clarify the purpose of these commands

**Comment by aatmasaat** [comment]
ahh, since install and remove commands were working fine I assumed other commands will work with standard repo.

the commands make sense now as [lure-repo](https://github.com/Arsen6331/lure-repo) has limited packages as of now.

thank you
