### ISSUE TITLE
lure can't download source from gitflic

### ISSUE THREAD

**Issue by xpamych** [Arsen6331/lure#62]
![image](https://user-images.githubusercontent.com/16473797/220077807-281fd1db-bd1c-41e0-852f-b9a6dbb6ad58.png)

**Comment by Arsen6331** [comment]
I'm getting a 500 error from it even just trying with `git clone`, so I'm guessing gitflic is broken right now.

**Comment by xpamych** [comment]
![image](https://user-images.githubusercontent.com/16473797/220080903-631b41f1-a947-4ab0-bfce-8968651c48b1.png)

**Comment by Arsen6331** [comment]
Ah, in that case, the package is using the wrong URL. It's `hln-a`, not `hlna` like at https://gitflic.ru/project/xpamych/xpamych-lure-repo/blob?file=hlna-git%2Flure.sh#line-num-15

**Comment by xpamych** [comment]
I'm a damn blind man! Thx))
