### ISSUE TITLE
Other name for package build file

### ISSUE THREAD

**Issue by vaporup** [Arsen6331/lure#8]
`lure.sh` looks like a standalone shell script. I guess `PKGBUILD` would not be a good choice since it is not compatible with pacman and makedeb.

How about one of these?

- `PKGBUILD.lure`
- `PKGBUILDLURE`
- `PKGBUILD_LURE`
- `LUREPKGBUILD`
- `LURE_PKGBUILD`
- `LURE_BUILD`
- `LUREPKG`
- `LURE_PKG`

`lure.sh` could still be used for backward compatibility

**Comment by Arsen6331** [comment]
I chose `lure.sh` because the file is actually valid bash, and so that programs that detect file type \such as syntax highlighters, IDEs, etc. recognize it as a shell script and work accordingly

**Comment by vaporup** [comment]
I see. Usually that can also be achieved just with a shebang line
